/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  KlimaCarbonRetirements,
  KlimaCarbonRetirementsInterface,
} from "../KlimaCarbonRetirements";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "retirements",
    outputs: [
      {
        internalType: "uint256",
        name: "totalRetirements",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalCarbonRetired",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalClaimed",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class KlimaCarbonRetirements__factory {
  static readonly abi = _abi;
  static createInterface(): KlimaCarbonRetirementsInterface {
    return new utils.Interface(_abi) as KlimaCarbonRetirementsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): KlimaCarbonRetirements {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as KlimaCarbonRetirements;
  }
}
