import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Convo from "@theconvospace/sdk"

export default function Home() {

  let ConvoInstance = new Convo('CSCpPwHnkB3niBJiUjy92YGP6xVkVZbWfK8xriDO');

  return (
    <div className={styles.container}>
      <Head>
        <title>Convo Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://theconvo.space" target="_blank">Convo Space!</a>
        </h1>

        <p className={styles.description}>
          Get started by opening the console <code className={styles.code}>Ctrl/Cmd+Shift+I</code> on this page.
        </p>

        <div className={styles.grid}>
          <div onClick={() => {
            console.log(ConvoInstance.getApiKey())
          }} className={styles.card}>
            <h2>Print API Key &rarr;</h2>
            <p>Print the API key used to configure the Convo Instance.</p>
          </div>

          <div onClick={() => {
            ConvoInstance.auth.validate("0xa28992A6744e36f398DFe1b9407474e1D7A3066b", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMHhhMjg5OTJBNjc0NGUzNmYzOThERmUxYjk0MDc0NzRlMUQ3QTMwNjZiIiwiY2hhaW4iOiJldGhlcmV1bSIsImlhdCI6MTYzMzExNDQwMywiZXhwIjoxNjMzMjAwODAzfQ.ki5DSchd08ujU4i1zRx2uUgXiSCMaLjfLpZRE9rOtRQ").then(console.log);
          }} className={styles.card}>
            <h2>Validate Auth &rarr;</h2>
            <p>Validate an Authentication Token using the SDK.</p>
          </div>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
