name: Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Benchmark
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2
        with:
          version: 7.1.7

      - name: Install Workspace Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Build SDK Package
        run: cd ./packages/sdk && pnpm build:tsc

      - name: Run Benchmarks
        env:
          DEEPDAO_API_KEY: ${{ secrets.DEEPDAO_API_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}
          CNVSEC_ID: ${{ secrets.CNVSEC_ID }}
          BITQUERY_API_KEY: ${{ secrets.BITQUERY_API_KEY }}
        run: node ./benchmarks/benchmark.js
