name: Deno Valist Release

on:
  push:
    branches: []

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - run: echo "TIMESTAMP=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - uses: valist-io/valist-github-action@v2
        with:
          rpc-url: https://rpc.valist.io/polygon
          private-key: ${{ secrets.VALIST_RELEASER_PK }}
          account: theconvospace
          project: sdk-deno
          release: ${{ env.TIMESTAMP }}
          files: './packages/sdk-deno/**/**'
