name: Deno Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: test-${{ matrix.os }}-${{ matrix.deno }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Test on the latest stable, and nightly
        deno: [v1.x, canary]
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - run: deno --version

      - name: Run tests
        run: deno test mod_test.ts --allow-net
