name: Node Test

on:
  push:
    branches: [ main ]
    paths:
    - 'packages/**/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'packages/**/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 19.x]

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Workspace Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install --filter "{packages/**}"

      - name: Build SDK Package
        run: cd ./packages/sdk && pnpm build

      - name: Generate Bundle Stats
        run: cd ./packages/sdk && pnpm bundlestats

      - uses: actions/upload-artifact@v3
        with:
          name: stats-sdk.html
          path: ./packages/sdk/stats.html

      - name: Build React Package
        run: cd ./packages/react && pnpm build

      - name: Generate Bundle Stats
        run: cd ./packages/react && pnpm bundlestats

      - uses: actions/upload-artifact@v3
        with:
          name: stats-react.html
          path: ./packages/react/stats.html
